export const BE_LIGHT = 'BE_LIGHT'
export const BE_THIN = 'BE_THIN'
export const BE_REGULAR = 'BE_REGULAR'
export const BE_MEDIUM = 'BE_MEDIUM'
export const BE_SEMIBOLD = 'BE_SEMIBOLD'
export const BE_BOLD = 'BE_BOLD'
